package com.retro.finder

import java.io.File
import java.net.URL
import java.util.concurrent.Executors

import dispatch.{Http, url, _}
import org.joda.time.DateTime
import org.json4s.jackson.JsonMethods._
import org.json4s.{DefaultFormats, _}

import scala.collection.mutable.ListBuffer
import scala.concurrent.ExecutionContext
import scala.sys.process._
//import scala.concurrent.ExecutionContext.Implicits.global


/**
 * Created by martin on 23/04/15.
 */
object Main extends App{

  def futureMethod(i: Int, tag: String)(implicit time:DateTime)= {
    implicit val context = ExecutionContext.fromExecutor(Executors.newFixedThreadPool(100))
    val route = url("http://api.tumblr.com/v2/tagged")
      .addQueryParameter("api_key", "9dzfrAgBkowach2km4x22ZYloEDRRy9S2HWoOdXGO3Fmvcgxl8")
      .addQueryParameter("limit", "20")
      .addQueryParameter("before", time.minusDays(i).getMillis.toString)
      .addQueryParameter("tag", tag).GET

    val r = Http(route OK as.String).either
    r
  }


  override def main(args :Array[String]) = {

    implicit val formats = DefaultFormats

    //val tag = "ciberpunk"




    val tagList = List("Web of Angels by John M. Ford",
      "The Ware Tetralogy by Rudy Rucker",
      "Software",
      "Wetware",
      "Freeware",
      "Realware",
      "Dr. Adder",
      "Sprawl trilogy by William Gibson",
      "Neuromancer",
      "Count Zero",
      "Mona Lisa Overdrive",
      "Schismatrix",
      "Eclipse Trilogy",
      "Psion",
      "Hardwired series by Walter Jon Williams",
      "Hardwired",
      "Voice of the Whirlwind",
      "Solip:System",
      "Mindplayers",
      "The Glass Hammer",
      "The Marîd Audran series by George Alec Effinger",
      "When Gravity Fails",
      "A Fire in the Sun",
      "The Exile Kiss",
      "Little Heroes",
      "Islands in the Net",
      "My Cousin, My Gastroenterologist",
      "Synners",
      "Fools",
      "Snow Crash",
      "Bridge trilogy by William Gibson",
      "Virtual Light",
      "Idoru",
      "All Tomorrow's Parties",
      "Heavy Weather",
      "Trouble and Her Friends",
      "Blade Runner 2: The Edge of Human",
      "Blade Runner 3: Replicant Night",
      "Blade Runner 4: Eye and Talon",
      "Fairyland",
      "The Diamond Age",
      "Holy Fire",
      "Night Sky Mine",
      "Noir",
      "One of Us",
      "Starfish",
      "Chimera",
      "Altered Carbon",
      "River of Gods",
      "Cyberabad Days",
      "Accelerando",
      "Glasshouse",
      "The Mirrored Heavens",
      "Burning Chrome",
      "Mirrorshades: The Cyberpunk Anthology",
      "Patterns",
      "Crystal Express",
      "Storming the Reality Studio: A Casebook of Cyberpunk & Postmodern Science Fiction",
      "Hackers",
      "Altered States: a cyberpunk sci-fi anthology",
      "Akira",
      "Ghost in the Shell",
      "Neuromancer",
      "Battle Angel Alita",
      "Transmetropolitan",
      "Blame!",
      "NOiSE",
      "Biomega",
      "Singularity 7",
      "The Surrogates",
      "Magazines and journals",
      "Mondo 2000",
      "Ctheory",
      "Audiovisual media",
      "THX 1138",
      "The Terminal Man",
      "Logan's Run",
      "Futureworld",
      "Saturn 3",
      "Escape from New York",
      "Burst City",
      "Blade Runner",
      "Tron",
      "Videodrome",
      "Brainstorm",
      "Runaway",
      "Brazil",
      "Trancers",
      "RoboCop",
      "The Running Man",
      "Cherry 2000",
      "Cyborg",
      "Gunhed",
      "Circuitry Man",
      "Total Recall",
      "RoboCop 2",
      "Hardware",
      "Megaville",
      "Until the End of the World",
      "964 Pinocchio",
      "Freejack",
      "The Lawnmower Man",
      "Split Second",
      "Nemesis",
      "Fortress",
      "RoboCop 3",
      "Demolition Man",
      "Cyborg 2",
      "Plughead Rewired: Circuitry Man II",
      "Timecop",
      "Johnny Mnemonic",
      "Judge Dredd",
      "Nemesis 2: Nebula",
      "Virtuosity",
      "Strange Days",
      "Hackers",
      "Cyborg 3: The Recycler",
      "Terminal Justice",
      "The Lawnmower Man 2: Beyond Cyberspace",
      "Nemesis 3: Prey Harder",
      "Escape from Los Angeles",
      "Omega Doom",
      "Nemesis 4: Death Angel",
      "Nirvana",
      "The Fifth Element",
      "Gattaca",
      "Deathline",
      "Pi",
      "Dark City",
      "Andromedia",
      "Skyggen",
      "New Rose Hotel",
      "The Matrix",
      "eXistenZ",
      "The Thirteenth Floor",
      "Bicentennial Man",
      "I.K.U.",
      "Avalon",
      "A.I. Artificial Intelligence",
      "Electric Dragon 80.000 V",
      "Impostor",
      "Dead or Alive: Final",
      "Minority Report",
      "Resurrection of the Little Match Girl",
      "Cypher",
      "Equilibrium",
      "The Matrix Reloaded",
      "All Tomorrow's Parties",
      "Code 46",
      "Natural City",
      "The Matrix Revolutions",
      "Paycheck",
      "Paranoia 1.0",
      "Immortal",
      "I, Robot",
      "Godzilla: Final Wars",
      "Avatar",
      "The Island",
      "Æon Flux",
      "Ultraviolet",
      "A Scanner Darkly",
      "Chrysalis",
      "The Gene Generation",
      "Eden Log",
      "Sleep Dealer",
      "Tokyo Gore Police",
      "Babylon A.D.",
      "Gamer",
      "Surrogates",
      "Hardwired",
      "Repo Men",
      "Tron: Legacy",
      "In Time",
      "Dredd",
      "Oblivion",
      "Elysium",
      "The Zero Theorem",
      "Transcendence",
      "Automata",
      "Chappie",
      "Megazone 23",
      "Neo Tokyo",
      "Bubblegum Crisis",
      "Bubblegum Crisis Tokyo 2040",
      "Akira",
      "Cyber City Oedo 808",
      "Silent Möbius",
      "Genocyber",
      "Macross Plus",
      "Ghost in the Shell",
      "Ghost in the Shell",
      "Ghost in the Shell 2: Innocence",
      "Ghost in the Shell: Stand Alone Complex",
      "Ghost in the Shell: Stand Alone Complex",
      "Ghost in the Shell: S.A.C. 2nd GIG",
      "Ghost in the Shell: Stand Alone Complex - Solid State Society",
      "Ghost in the Shell: Arise",
      "Serial Experiments Lain",
      "Batman Beyond",
      "Dennō Coil",
      "Metropolis",
      "The Animatrix",
      "Heat Guy J",
      "Parasite Dolls",
      "Texhnolyze",
      "Wonderful Days",
      "Code Lyoko",
      "Burst Angel",
      "Fragile Machine",
      "Ergo Proxy",
      "Aachi & Ssipak",
      "Paprika",
      "Renaissance",
      "Vexille",
      "Technotise: Edit & I",
      "Mardock Scramble",
      "Steins;Gate",
      "Psycho-Pass",
      "World on a Wire",
      "Overdrawn at the Memory Bank",
      "Max Headroom: 20 Minutes into the Future",
      "Max Headroom",
      "Wild Palms",
      "TekWar",
      "RoboCop: The Series",
      "VR.5",
      "Welcome to Paradox",
      "Kill Switch",
      "First Person Shooter",
      "Harsh Realm",
      "Total Recall 2070",
      "Dark Angel",
      "Star Trek: Voyager",
      "Unimatrix Zero",
      "RoboCop: Prime Directives",
      "Charlie Jade",
      "Dollhouse",
      "Caprica",
      "Person of Interest",
      "Continuum",
      "H+: The Digital Series",
      "Almost Human",
      "Die Gstettensaga: The Rise of Echsenfriedl",
      "Angelspit[",
      "Atari Teenage Riot",
      "Buck-Tick",
      "Clock DVA",
      "Covenant",
      "Death Grips",
      "Dope Stars Inc.",
      "Front Line Assembly",
      "Fear Factory",
      "Haujobb",
      "Headscan",
      "Iron Savior",
      "Juno Reactor",
      "Left Spine Down",
      "Nine Inch Nails",
      "Psydoll",
      "Sigue Sigue Sputnik",
      "Voivod",
      "Yellow Magic Orchestra",
      "Releases",
      "Blade Runner by Vangelis ",
      "Cyberpunk by Billy Idol",
      "Outside by David Bowie",
      "Transverse City by Warren Zevon",
      "Year Zero by Nine Inch Nails",
      "Psychic City",
      "The Screamer",
      "Imitation City",
      "Hoshi wo Miru Hito",
      "Megami Tensei",
      "Neuromancer",
      "Snatcher",
      "Flashback",
      "DreamWeb",
      "Shadowrun",
      "Shadowrun",
      "Shadowrun",
      "Shadowrun Returns",
      "Syndicate",
      "Syndicate Wars",
      "Syndicate",
      "Beneath a Steel Sky",
      "Burn:Cycle",
      "Delta V",
      "System Shock",
      "CyberMage: Darklight Awakening",
      "Johnny Mnemonic: The Interactive Action Movie",
      "Blade Runner",
      "Final Fantasy VII",
      "System Shock 2",
      "Deus Ex",
      "Deus Ex: Invisible War",
      "Deus Ex: Human Revolution",
      "Deus Ex: The Fall",
      "Metal Gear Solid 2: Sons of Liberty",
      "Uplink",
      "Neocron",
      "Enter the Matrix",
      "Dystopia",
      "System Rush",
      "Crackdown",
      "Crackdown 2",
      "Gemini Rue",
      "Hard Reset",
      "Far Cry 3: Blood Dragon",
      "Cypher",
      "Remember Me",
      "Watch Dogs",
      "Dex",
      "Satellite Reign",
      "Cyberpunk 2077",
      "Cyberpunk 2020",
      "Shadowrun",
      "Cyberspace",
      "GURPS Cyberpunk",
      "Metal Head",
      "Tokyo NOVA",
      "Sindome",
      "Dandy Dust",
      "Ultra-Toxic",
      "Zoetrope",
      "Automatons",
      "TokyoPlastic",
      "The Windup Girl",
      "Ribofunk",
      "The Movement of Mountains and The Brains of Rats by Michael Blumlein",
      "Clade and Crache",
      "White Devils",
      "The Xenogenesis",
      "Doktor Sleepless",
      "Fluorescent Black",
      "Neon Genesis Evangelion",
      "Alien",
      "Aliens",
      "Alien&sup3;",
      "Alien Ressurection",
      "Prometheus",
      "David Cronenberg",
      "Videodrome",
      "Crash",
      "eXistenZ",
      "John Carpenter",
      "Escape from New York",
      "They Live",
      "Escape from LA",
      "The Matrix",
      "The Matrix",
      "The Matrix Reloaded",
      "The Matrix Revolutions",
      "The Animatrix",
      "Philip K. Dick",
      "Blade Runner",
      "Impostor",
      "Minority Report",
      "Next",
      "Paycheck",
      "Radio Free Albermuth",
      "Screamers",
      "A Scanner Darkly",
      "Total Recall",
      "Total Recall",
      "Robocop",
      "Robocop",
      "Robocop 2",
      "Robocop 3",
      "Robocop",
      "The Terminator",
      "The Terminator",
      "Terminator 2: Judgement Day",
      "Terminator 3: Rise of the Machines",
      "Terminator Salvation",
      "TRON",
      "TRON",
      "TRON Legacy",
      "William Gibson",
      "Johnny Mnemonic",
      "New Rose Hotel",
      "No Maps for These Territories",
      "Tomorrow Calling",
      "Other movies",
      "Aeon Flux",
      "Automata",
      "Babylon A.D.",
      "Brazil",
      "Chappie",
      "Circuitry Man",
      "Circuitry Man 2: Plughead Rewired",
      "Class of 1999",
      "Cyborg",
      "Cyborg 2",
      "Cyborg 3: The Recycler",
      "Cypher",
      "Dredd",
      "Elysium",
      "Ex Machina",
      "The Fifth Element",
      "Fortress",
      "Hardware",
      "Hardwired",
      "Judge Dredd",
      "Kung Fury",
      "The Lawnmower Man",
      "The Lawnmower Man 2: Beyond Cyberspace",
      "Megaville",
      "Nemesis",
      "Nirvana",
      "Overdrawn at the Memory Bank",
      "Renaissance",
      "Repo! The Genetic Opera",
      "The Running Man",
      "Sleep Dealer",
      "Split Second",
      "Strange Days",
      "The 13th Floor",
      "Transcendence",
      "Until the End of the World",
      "Webmaster / Skyggen",
      "Japanese Cyberpunk",
      "964 Pinocchio",
      "Avalon",
      "Burst City",
      "Death Powder",
      "The Gene Generation",
      "Gunhed",
      "The Machine Girl",
      "RoboGeisha",
      "Rubber's Lover",
      "Tetsuo: The Iron Man",
      "Tetsuo II: Body Hammer",
      "Tetsuo the Bullet Man",
      "Proto-Cyberpunk Movies",
      "Alphaville",
      "Altered States",
      "A Clockwork Orange",
      "Colossus: The Forbin Project",
      "Dark Star",
      "Death Race 2000",
      "Future Shock",
      "Futureworld",
      "La Jetee",
      "Metropolis",
      "Giorgio Moroder Presents Metropolis",
      "Outland",
      "Soylent Green",
      "The Terminal Man",
      "THX-1138",
      "Westworld",
      "World on a Wire",
      "Hacker Movies",
      "Antitrust",
      "Arcade",
      "Brainscan",
      "Die Hard 4",
      "Electric Dreams",
      "Firewall",
      "Ghost in the Machine",
      "Hackers",
      "Masterminds",
      "The Net",
      "The Net 2.0",
      "Pi",
      "Pirates of Silicon Valley",
      "Sneakers",
      "The Social Network",
      "Swordfish",
      "Takedown/Track Down",
      "Terminal Entry",
      "Untraceable",
      "Wargames",
      "Wargames: The Dead Code",
      "The Zero Theorum",
      "Documentaries",
      "Cyberpunk",
      "No Maps for These Territories",
      "Related and of Interest",
      "12 Monkeys",
      "Battle Royale",
      "Beyond the Black Rainbow",
      "Black Rain",
      "The Children of Men",
      "The City of Lost Children",
      "Decoder",
      "District 9",
      "District B-13",
      "Equilibrium",
      "Inception",
      "I'm a Cyborg, but That's Ok",
      "Liquid Sky",
      "Moon",
      "Repo Man",
      "Southland Tales",
      "The Thing",
      "Wax or the discovery of Television Among the Bees",
      "William S. Burroughs: A Man Within",
      "A.D. Police",
      "Blame!",
      "Digimortal",
      "Megazone 23",
      "Mardock Scramble",
      "NOiSE",
      "NSE: Net Sphere Engineer",
      "Silent Möbius",
      "Texhnolyze",
      "Angel Cop",
      "Armitage III",
      "Armitage III: Dual Matrix",
      "Battle Angel",
      "Black Magic M-66",
      "Blame!",
      "Cowboy Bebop",
      "Cyber City Oedo 808",
      "Dead Leaves",
      "Dennō Coil",
      "Desert Punk - Netflix",
      "Dirty Pair",
      "Dirty Pair Flash",
      "Dirty Pair: Project Eden",
      "Dominion Tank Police",
      "Eden: It's an Endless World!",
      "Ergo Proxy",
      "Genocyber",
      "Goku Midnight Eye",
      "Heat Guy J",
      "Mardock Scramble",
      "Megazone 23",
      "Real Drive",
      "Patlabor",
      "Psycho-Pass",
      "Serial Experiments Lain",
      "Silent Möbius",
      "Technotise: Edit and I",
      "Thexnolize",
      "Un-Go",
      "Vexille",
      "Viper's Creed")

    //val req = Http("http://api.tumblr.com/v2/blog/rekall.tumblr.com/posts/photo").param("api_key","fuiKNFp9vQFvjLNvx4sUwti4Yb5yGutBN4Xh10LXZhhRKjWlV4").asString
    //for(offset <- 0 to 5200 by pageSize){
    //for(tag <- tagList){
      //Future{
        //println(s"$offset - $pageSize")
    implicit val time = DateTime.now()
    implicit val context = ExecutionContext.fromExecutor(Executors.newFixedThreadPool(4))


    var downloaded = ListBuffer[String]()


    for(i <- 0 to 365 * 2 by 30; tag <- tagList){
    //for(i <- 0 to 1; tag <- tagList.take(1)){
      //val tag = "ciberpunk"
      //println(i+" "+tag)
        futureMethod(i, tag).map{
          case Left(e) => println(e.getMessage); e.printStackTrace();
          case Right(req) =>{
            val json = parse(req)
            (json \ "response").extractOpt[List[Response]].map{ responses =>
              val filteredResponses = responses.filter( _.note_count > 1000 )
              val parsed = filteredResponses.flatMap{_.photos.map(_.original_size.url)}

              val nonRepeatedParsed = parsed.diff(downloaded)
              downloaded++=nonRepeatedParsed
              parsed.foreach{url => new URL(url) #> new File(url.split("/").last) !!}
            }
          }
        }
      //}
    }
  }
}


case class Response(note_count :Int, photos:List[Photo])

case class Photo(original_size :Size)

case class Size(url :String)